Fix installation error due to missing CHANGES.rst. (#402)
Fixes:
Traceback (most recent call last):
  File "/home/buildroot/buildroot/output/build/python-aiohttp-jinja2-1.4.1/setup.py", line 41, in <module>
    long_description="\n\n".join((read("README.rst"), read("CHANGES.rst"))),
  File "/home/buildroot/buildroot/output/build/python-aiohttp-jinja2-1.4.1/setup.py", line 29, in read
    return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/home/buildroot/buildroot/output/build/python-aiohttp-jinja2-1.4.1/CHANGES.rst'

Co-authored-by: Andrew Svetlov <andrew.svetlov@gmail.com>